xString = input("Enter a number :  ")
x=int(xString)
yString = input("Enter a second number : ")
y=int(yString)
print('The quotient of ', xString,' and ', yString,' is ',x//y, ' with a remainder of ',x%y, sep='')